### PR TITLE
completed lab4

### PR DESCRIPTION
**Pull request by emilio-lobato**
This is my completed lab4. I received a couple of failures when using test_dir, for 6.1 and 6.4. Both are about object names that I didn't see to use in the instructions but, when investigating, still seem to be what you were after. I hope that's ok.

### CODE REVIEW

**Comment by dhicks** [comment]
Can you say more about the errors in 6.1 and 6.4?

**Comment by emilio-lobato** [comment]
Below is the text I get for the errors. I didn't see in the instructions to name things 'dataf_fct' or 'top_10_soln' and I assume that's all the errors are in reference to.

test_lab.R:53: failure: 6.1. `dataf_smol` contains all the factor and numeric variables from `dataf`
`dataf_smol` not identical to select(dataf_fct, where(is.factor), where(is.numeric)).
Names: 36 string mismatches
Component 1: Attributes: < target is NULL, current is list >
Component 1: target is numeric, current is factor
Component 2: Mean relative difference: 0.9943193
Component 3: Mean relative difference: 4.153161
Component 4: Mean relative difference: 0.01399429
Component 5: Mean relative difference: 18.62737
Component 6: Mean relative difference: 24.49101
Component 7: Mean relative difference: 1.069776
...

test_lab.R:72: failure: 6.4. Top 10 variables most strongly correlated with sale price
`top_10` not equal to `top_10_soln`.
Component “covar”: 10 string mismatches
Component “Sale_Price”: Mean relative difference: 0.2094692

**Comment by dhicks** [comment]
I cloned your code and ran it on my machine, and don't see these error messages.  If you reset the R session and run `testthat::test_dir('tests')` do they still appear?

**Comment by emilio-lobato** [comment]
No, the error messages no longer show up. I should really internalize the whole "have I tried turning it off and on again" thing, I guess.

**Pull request closed without merging**
